---
collapsible_nav: true
default_owner_slack: "#observability-platform"
enable_search: true
full_service_name: Observability Platform
github_branch: main
github_repo: ministryofjustice/observability-platform
header_links:
  GitHub: https://github.com/ministryofjustice/observability-platform
  Slack: https://moj.enterprise.slack.com/archives/C05P1RUV0UD
host: https://observability-platform.service.justice.gov.uk
max_toc_heading_level: 3
owner_slack_workspace: mojdt
phase: INTERNAL
prevent_indexing: true
service_link: /
service_name: Observability Platform
show_contribution_banner: true
show_expiry: true
show_govuk_logo: false
show_review_banner: true
